# Generated by Django 3.1.5 on 2021-06-08 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='PK id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=40)),
                ('age', models.IntegerField(help_text='Age of pets')),
                ('type', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], default='Pet', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created time')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='PK id', primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='default.jpg', upload_to='PetsPhoto')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='catalog.pet')),
            ],
        ),
    ]
